### ISSUE TITLE
Persistent memory limits reached, server restartes, etc, with DDMRP Odoo 13 code

### ISSUE THREAD

**Issue by walkerblackwell** [OCA/ddmrp#195]
## Module

DDMRP

## Describe the bug

There are several bugs that may all be tied together. Originally I had noticed that DDMRP de-activated all crons. Well I found out finally that this was because it pretty quickly hits the memory limit on an odoo.sh install with 8 workers activated. This is without QUEUE installed and just 1 buffer profile. 

Also, when you create a buffer profile and go to edit it, it restarts the server on save when you change lead time or cycle time. The only way to edit a buffer profile after creation is to re-import it over or do a mass_edit. 

This also causes memory limit issues. 

I put this on an external test server with 32GB of ram and maxed out odoo config and I had the same issue. Once the server hits the memory limit it goes into a restart loop and will not settle down until DDMRP is entirely uninstalled. There is a memory leak somewhere. Anyone else having these issues?

## To Reproduce
**Affected versions**:

Odoo 13 so far . . .

1. Install DDMRP
2. Have odoo.sh studio installed, enterprise edition . . .
3. Create a profile.
4. Edit the profile (you will see the the server reboot.
5. Wait till some crons run, eventually you will see memory limits hit and server reboot cycle start.

I noticed this memory leak also directly on the machine stats. It will fill the ram entirely with junk "cache" data that I would then manually purge each night . . . It degraded the server for sure. 

**Expected behavior**

Ideally DDMRP would act friendly RAM-wise . . . It's possibly interacting with some other module here (MRP related maybe) but not sure . . . I would love other's experience here or if they have similar issues.

**Comment by walkerblackwell** [comment]
I updated Bokeh to most recent version and this resolved about 1/8th of the memory leak trips . . . but still just kills all odoo instances I can muster up . . .

**Comment by walkerblackwell** [comment]
I think I narrowed this down to Bokeh and the hooks file causing memory leak as the module is loaded. I removed this and things seem to work. This needs looking at in v13.

**Comment by LoisRForgeFlow** [comment]
Hi @walkerblackwell 

I have't faced such an issue, may it be something specific of odoo.sh? 

> I removed this and things seem to work.

What did you remove? bokeh?

Thanks,

**Comment by walkerblackwell** [comment]
Honestly I have had not much time to debug (it happens on 32GB 8CPU non-odoo.sh machine too) but I reloaded this on odoo.sh and re-installed DDMRP and this is what I get once any of the scheduled actions executes.

2022-03-31 12:32:13,045 5599 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module: Couldn't load module ddmrp
2022-03-31 12:32:13,045 5599 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module:
2022-03-31 12:32:13,047 5599 WARNING walkerblackwell-v13-production-1141029 odoo.modules.loading: Transient module states were reset
2022-03-31 12:32:13,047 5599 ERROR walkerblackwell-v13-production-1141029 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 26, in <module>
    from ..core.properties import Any, Auto, Either, Enum, Int, List, Seq, Instance, String, Tuple
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/properties.py", line 245, in <module>
    from .property.auto import Auto; Auto
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/property/auto.py", line 28, in <module>
    from .enum import Enum
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/property/enum.py", line 29, in <module>
    from .. import enums
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/enums.py", line 81, in <module>
    from .. import colors, palettes
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
2022-03-31 12:32:13,056 5599 CRITICAL walkerblackwell-v13-production-1141029 odoo.service.server: Failed to initialize database `walkerblackwell-v13-production-1141029`. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 26, in <module>
    from ..core.properties import Any, Auto, Either, Enum, Int, List, Seq, Instance, String, Tuple
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/properties.py", line 245, in <module>
    from .property.auto import Auto; Auto
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/property/auto.py", line 28, in <module>
    from .enum import Enum
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/property/enum.py", line 29, in <module>
    from .. import enums
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/core/enums.py", line 81, in <module>
    from .. import colors, palettes
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
2022-03-31 12:32:13,060 5599 WARNING walkerblackwell-v13-production-1141029 odoo.service.server: Server memory limit (2659151872) reached.
2022-03-31 12:32:13,065 5599 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: loading 1 modules...
2022-03-31 12:32:13,078 5599 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries
2022-03-31 12:32:13,339 5599 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: loading 224 modules... 
2022-03-31 12:32:14,100 5599 WARNING walkerblackwell-v13-production-1141029 odoo.service.server: Server memory limit (2659151872) reached.

**Comment by walkerblackwell** [comment]
Then it just cycles through reboots like this:

2022-03-31 12:37:39,680 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module: Couldn't load module ddmrp
2022-03-31 12:37:39,680 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module:
2022-03-31 12:37:39,682 5698 WARNING walkerblackwell-v13-production-1141029 odoo.modules.loading: Transient module states were reset
2022-03-31 12:37:39,682 5698 ERROR walkerblackwell-v13-production-1141029 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 28, in <module>
    from ..models import ColumnDataSource, Plot, Title, Tool, GraphRenderer
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/models/__init__.py", line 49, in <module>
    from ..model import Model
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/model.py", line 37, in <module>
    from .events import Event
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
2022-03-31 12:37:39,689 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.service.server: Failed to initialize database `walkerblackwell-v13-production-1141029`. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 28, in <module>
    from ..models import ColumnDataSource, Plot, Title, Tool, GraphRenderer
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/models/__init__.py", line 49, in <module>
    from ..model import Model
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/model.py", line 37, in <module>
    from .events import Event
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
2022-03-31 12:37:39,694 5698 WARNING walkerblackwell-v13-production-1141029 odoo.service.server: Server memory limit (2659155968) reached.
2022-03-31 12:37:39,695 5698 INFO walkerblackwell-v13-production-1141029 odoo.service.server: Dumping stacktrace of limit exceeding threads before reloading
2022-03-31 12:37:39,697 5698 INFO walkerblackwell-v13-production-1141029 odoo.tools.misc: 
# Thread: <_MainThread(MainThread, started 139757661931328)> (db:walkerblackwell-v13-production-1141029) (uid:n/a) (url:n/a)
File: "/usr/local/bin/odoo-rpc", line 47, in <module>
  odoo.service.server.start(preload=[db])
File: "/home/odoo/src/odoo/odoo/service/server.py", line 1289, in start
  rc = server.run(preload, stop)
File: "/home/odoo/src/odoo/odoo/service/server.py", line 537, in run
  dumpstacks(thread_idents=[thread.ident for thread in self.limits_reached_threads])
File: "/home/odoo/src/odoo/odoo/tools/misc.py", line 964, in dumpstacks
  for line in extract_stack(stack):
2022-03-31 12:37:39,697 5698 INFO walkerblackwell-v13-production-1141029 odoo.service.server: Initiating server reload
2022-03-31 12:37:40,399 29132 INFO walkerblackwell-v13-production-1141029 werkzeug: 157.55.39.202 - - [31/Mar/2022 12:37:40] "GET /blog/ink-on-paper-blog-2/tag/printmaking-122,conecolor-hdr-128,tech-support-129,rips-156 HTTP/1.0" 200 - 646 0.977 0.558
2022-03-31 12:37:40,443 5698 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2022-03-31 12:37:40,744 5698 INFO ? odoo.service.server: HTTP service (werkzeug) running through socket activation
2022-03-31 12:37:40,764 5698 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: loading 1 modules...
2022-03-31 12:37:40,775 5698 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries
2022-03-31 12:37:40,864 5698 INFO walkerblackwell-v13-production-1141029 odoo.modules.loading: loading 224 modules...
2022-03-31 12:37:41,339 4545 INFO walkerblackwell-v13-production-1141029 werkzeug: 172.99.225.73 - - [31/Mar/2022 12:37:41] "POST /longpolling/poll HTTP/1.0" 200 - 19 0.024 0.019
2022-03-31 12:37:41,378 4545 INFO walkerblackwell-v13-production-1141029 werkzeug: 197.232.90.252 - - [31/Mar/2022 12:37:41] "GET /how-to-initial-fill-your-printer HTTP/1.0" 200 - 67 0.040 0.120
2022-03-31 12:37:41,519 4545 INFO walkerblackwell-v13-production-1141029 werkzeug: 199.21.137.46 - - [31/Mar/2022 12:37:41] "POST /longpolling/poll HTTP/1.0" 200 - 8 0.003 0.009
2022-03-31 12:37:42,703 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module: Couldn't load module ddmrp
2022-03-31 12:37:42,704 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.modules.module:
2022-03-31 12:37:42,705 5698 WARNING walkerblackwell-v13-production-1141029 odoo.modules.loading: Transient module states were reset
2022-03-31 12:37:42,705 5698 ERROR walkerblackwell-v13-production-1141029 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 28, in <module>
    from ..models import ColumnDataSource, Plot, Title, Tool, GraphRenderer
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/models/__init__.py", line 49, in <module>
    from ..model import Model
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/model.py", line 37, in <module>
    from .events import Event
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError
2022-03-31 12:37:42,710 5698 CRITICAL walkerblackwell-v13-production-1141029 odoo.service.server: Failed to initialize database `walkerblackwell-v13-production-1141029`. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/addons/ddmrp/__init__.py", line 1, in <module>
    from . import models
  File "/home/odoo/src/user/addons/ddmrp/models/__init__.py", line 3, in <module>
    from . import mrp_production
  File "/home/odoo/src/user/addons/ddmrp/models/mrp_production.py", line 7, in <module>
    from .stock_buffer import _PRIORITY_LEVEL
  File "/home/odoo/src/user/addons/ddmrp/models/stock_buffer.py", line 18, in <module>
    from bokeh.plotting import figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 57, in <module>
    from . import figure as _figure
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 28, in <module>
    from ..models import ColumnDataSource, Plot, Title, Tool, GraphRenderer
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/models/__init__.py", line 49, in <module>
    from ..model import Model
  File "/home/odoo/.local/lib/python3.6/site-packages/bokeh/model.py", line 37, in <module>
    from .events import Event
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError
2022-03-31 12:37:42,714 5698 WARNING walkerblackwell-v13-production-1141029 odoo.service.server: Server memory limit (2659160064) reached.
2022-03-31 12:37:42,714 5698 INFO walkerblackwell-v13-production-1141029 odoo.service.server: Dumping stacktrace of limit exceeding threads before reloading
2022-03-31 12:37:42,715 5698 INFO walkerblackwell-v13-production-1141029 odoo.tools.misc: 
# Thread: <_MainThread(MainThread, started 140173958096704)> (db:walkerblackwell-v13-production-1141029) (uid:n/a) (url:n/a)
File: "/usr/local/bin/odoo-rpc", line 47, in <module>
  odoo.service.server.start(preload=[db])
File: "/home/odoo/src/odoo/odoo/service/server.py", line 1289, in start
  rc = server.run(preload, stop)
File: "/home/odoo/src/odoo/odoo/service/server.py", line 537, in run
  dumpstacks(thread_idents=[thread.ident for thread in self.limits_reached_threads])
File: "/home/odoo/src/odoo/odoo/tools/misc.py", line 964, in dumpstacks
  for line in extract_stack(stack):
2022-03-31 12:37:42,715 5698 INFO walkerblackwell-v13-production-1141029 odoo.service.server: Initiating server reload
2022-03-31 12:37:42,808 29132 INFO walkerblackwell-v13-production-1141029 werkzeug: 114.119.146.19 - - [31/Mar/2022 12:37:42]
