### ISSUE TITLE
run mrp multi level raise UserError

### ISSUE THREAD

**Issue by jeffery9** [OCA/ddmrp#26]
raise UserError ```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "E:\_odoo\odoo\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\_odoo\odoo\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "E:\_odoo\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "E:\_odoo\odoo\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "E:\_odoo\odoo\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\_odoo\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\_odoo\odoo\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\_odoo\odoo\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "E:\_odoo\odoo\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "E:\_odoo\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "E:\_odoo\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\_odoo\odoo\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "E:\_odoo\odoo\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "e:\_odoo\ddmrp\mrp_multi_level\wizards\mrp_multi_level.py", line 768, in run_mrp_multi_level
    self._mrp_final_process()
  File "e:\_odoo\ddmrp\mrp_multi_level\wizards\mrp_multi_level.py", line 736, in _mrp_final_process
    self._init_mrp_inventory(mrp_product)
  File "e:\_odoo\ddmrp\mrp_multi_level\wizards\mrp_multi_level.py", line 678, in _init_mrp_inventory
    group['mrp_date:day'])
  File "e:\_odoo\ddmrp\mrp_multi_level\wizards\mrp_multi_level.py", line 644, in _convert_group_date_to_default
    locale.setlocale(locale.LC_TIME, 'en_GB.UTF-8')
  File "C:\Python35\lib\locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

**Comment by LoisRForgeFlow** [comment]
This only happens in runbot, if you try on your local/server it should work.

Anyway, I should have a look to fix that in runbot too. Will come back to this when I have some spare time.

**Comment by yastri** [comment]
I've got same error 


>   File "/odoo/addons/manufacture/mrp_multi_level/wizards/mrp_multi_level.py", line 649, in _convert_group_date_to_default
>     locale.setlocale(locale.LC_TIME, 'en_GB.UTF-8')
>   File "/usr/lib/python3.6/locale.py", line 598, in setlocale
>     return _setlocale(category, locale)
> locale.Error: unsupported locale setting

**Comment by LoisRForgeFlow** [comment]
see https://github.com/OCA/ddmrp/issues/26#issuecomment-428507977

**Comment by LoisRForgeFlow** [comment]
This issue does not happen anymore as it has been corrected.
