### ISSUE TITLE
[10.0] DDMRP Buffer History Chart view

### ISSUE THREAD

**Issue by didierdonze** [OCA/ddmrp#4]
V10
Clicking on the Chart view of the report 'DDMRP Buffer History'  raises following error message:

```
Traceback (most recent call last):
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/models.py", line 1931, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/models.py", line 2021, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ddonze/nobackup/ddmrp/ddmrp10/lib/python2.7/site-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ORDER BY "id" is ambiguous
LINE 6:             ORDER BY "id" 
                             ^
```

**Comment by jonerikceberio** [comment]
Found the same problem in another module in v11, solved by adding rec_name to the class

**Comment by LoisRForgeFlow** [comment]
There is no V10 in this repository, so you are probably using the code at Eficent/ddmrp. Feel free to propose a PR there.
