### ISSUE TITLE
Uncaught Error: JSON object has wrong type string

### ISSUE THREAD

**Issue by missouriwind** [OCA/ddmrp#44]
In the land of indecipherable error messages, this one looks even more above average. It identifies as a Bokeh error - I have Bokeh installed. Going into Master Data > Stock Buffer Planning is fine:
![image](https://user-images.githubusercontent.com/41308074/60762422-6cbfea80-a02d-11e9-9d8b-bada8aac3f89.png)
When I click on the first item in my list I get the following error:

Error:
Uncaught Error: JSON object has wrong type string

https://mwands.us/web/content/51378-9870550/web.assets_backend.js:6753
Traceback:
Error: JSON object has wrong type string
    at Function.Document.from_json (https://mwands.us/web/content/51378-9870550/web.assets_backend.js:4794:272)
    at Object.exports.embed_items (https://mwands.us/web/content/51378-9870550/web.assets_backend.js:4824:182)
    at embed_document (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:10:28)
    at eval (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:14:13)
    at eval (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:29:11)
    at Object.safely (https://mwands.us/web/content/51378-9870550/web.assets_backend.js:6752:12)
    at fn (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:4:13)
    at eval (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:32:43)
    at eval (eval at <anonymous> (https://mwands.us/web/content/51095-5f8ed01/web.assets_common.js:625:213), <anonymous>:34:5)
    at eval (<anonymous>)

**Comment by missouriwind** [comment]
Current release of Bokeh is around 1.2.0. This needs 0.12.7.

Please excuse the interruption.....
